version: '3'
services:
  axum:
    image: jpalmucci/pokertimer:latest
    environment:
      - RUST_LOG=info
      - LEPTOS_SITE_ADDR=0.0.0.0:8443
    ports:
      - "443:8443"
    volumes:
      - ./certs:/app/certs
